<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Seed the countries table with all countries (ISO 3166-1 alpha-2).
     */
    public function run(): void
    {
        $countries = [
            ['country_name' => 'Afganistán', 'iso_code_2' => 'AF'],
            ['country_name' => 'Albania', 'iso_code_2' => 'AL'],
            ['country_name' => 'Alemania', 'iso_code_2' => 'DE'],
            ['country_name' => 'Andorra', 'iso_code_2' => 'AD'],
            ['country_name' => 'Angola', 'iso_code_2' => 'AO'],
            ['country_name' => 'Antigua y Barbuda', 'iso_code_2' => 'AG'],
            ['country_name' => 'Arabia Saudita', 'iso_code_2' => 'SA'],
            ['country_name' => 'Argelia', 'iso_code_2' => 'DZ'],
            ['country_name' => 'Argentina', 'iso_code_2' => 'AR'],
            ['country_name' => 'Armenia', 'iso_code_2' => 'AM'],
            ['country_name' => 'Australia', 'iso_code_2' => 'AU'],
            ['country_name' => 'Austria', 'iso_code_2' => 'AT'],
            ['country_name' => 'Azerbaiyán', 'iso_code_2' => 'AZ'],
            ['country_name' => 'Bahamas', 'iso_code_2' => 'BS'],
            ['country_name' => 'Bangladés', 'iso_code_2' => 'BD'],
            ['country_name' => 'Barbados', 'iso_code_2' => 'BB'],
            ['country_name' => 'Baréin', 'iso_code_2' => 'BH'],
            ['country_name' => 'Bélgica', 'iso_code_2' => 'BE'],
            ['country_name' => 'Belice', 'iso_code_2' => 'BZ'],
            ['country_name' => 'Benín', 'iso_code_2' => 'BJ'],
            ['country_name' => 'Bielorrusia', 'iso_code_2' => 'BY'],
            ['country_name' => 'Birmania', 'iso_code_2' => 'MM'],
            ['country_name' => 'Bolivia', 'iso_code_2' => 'BO'],
            ['country_name' => 'Bosnia y Herzegovina', 'iso_code_2' => 'BA'],
            ['country_name' => 'Botsuana', 'iso_code_2' => 'BW'],
            ['country_name' => 'Brasil', 'iso_code_2' => 'BR'],
            ['country_name' => 'Brunéi', 'iso_code_2' => 'BN'],
            ['country_name' => 'Bulgaria', 'iso_code_2' => 'BG'],
            ['country_name' => 'Burkina Faso', 'iso_code_2' => 'BF'],
            ['country_name' => 'Burundi', 'iso_code_2' => 'BI'],
            ['country_name' => 'Bután', 'iso_code_2' => 'BT'],
            ['country_name' => 'Cabo Verde', 'iso_code_2' => 'CV'],
            ['country_name' => 'Camboya', 'iso_code_2' => 'KH'],
            ['country_name' => 'Camerún', 'iso_code_2' => 'CM'],
            ['country_name' => 'Canadá', 'iso_code_2' => 'CA'],
            ['country_name' => 'Catar', 'iso_code_2' => 'QA'],
            ['country_name' => 'Chad', 'iso_code_2' => 'TD'],
            ['country_name' => 'Chile', 'iso_code_2' => 'CL'],
            ['country_name' => 'China', 'iso_code_2' => 'CN'],
            ['country_name' => 'Chipre', 'iso_code_2' => 'CY'],
            ['country_name' => 'Colombia', 'iso_code_2' => 'CO'],
            ['country_name' => 'Comoras', 'iso_code_2' => 'KM'],
            ['country_name' => 'Corea del Norte', 'iso_code_2' => 'KP'],
            ['country_name' => 'Corea del Sur', 'iso_code_2' => 'KR'],
            ['country_name' => 'Costa de Marfil', 'iso_code_2' => 'CI'],
            ['country_name' => 'Costa Rica', 'iso_code_2' => 'CR'],
            ['country_name' => 'Croacia', 'iso_code_2' => 'HR'],
            ['country_name' => 'Cuba', 'iso_code_2' => 'CU'],
            ['country_name' => 'Dinamarca', 'iso_code_2' => 'DK'],
            ['country_name' => 'Dominica', 'iso_code_2' => 'DM'],
            ['country_name' => 'Ecuador', 'iso_code_2' => 'EC'],
            ['country_name' => 'Egipto', 'iso_code_2' => 'EG'],
            ['country_name' => 'El Salvador', 'iso_code_2' => 'SV'],
            ['country_name' => 'Emiratos Árabes Unidos', 'iso_code_2' => 'AE'],
            ['country_name' => 'Eritrea', 'iso_code_2' => 'ER'],
            ['country_name' => 'Eslovaquia', 'iso_code_2' => 'SK'],
            ['country_name' => 'Eslovenia', 'iso_code_2' => 'SI'],
            ['country_name' => 'España', 'iso_code_2' => 'ES'],
            ['country_name' => 'Estados Unidos', 'iso_code_2' => 'US'],
            ['country_name' => 'Estonia', 'iso_code_2' => 'EE'],
            ['country_name' => 'Esuatini', 'iso_code_2' => 'SZ'],
            ['country_name' => 'Etiopía', 'iso_code_2' => 'ET'],
            ['country_name' => 'Filipinas', 'iso_code_2' => 'PH'],
            ['country_name' => 'Finlandia', 'iso_code_2' => 'FI'],
            ['country_name' => 'Fiyi', 'iso_code_2' => 'FJ'],
            ['country_name' => 'Francia', 'iso_code_2' => 'FR'],
            ['country_name' => 'Gabón', 'iso_code_2' => 'GA'],
            ['country_name' => 'Gambia', 'iso_code_2' => 'GM'],
            ['country_name' => 'Georgia', 'iso_code_2' => 'GE'],
            ['country_name' => 'Ghana', 'iso_code_2' => 'GH'],
            ['country_name' => 'Granada', 'iso_code_2' => 'GD'],
            ['country_name' => 'Grecia', 'iso_code_2' => 'GR'],
            ['country_name' => 'Guatemala', 'iso_code_2' => 'GT'],
            ['country_name' => 'Guinea', 'iso_code_2' => 'GN'],
            ['country_name' => 'Guinea Ecuatorial', 'iso_code_2' => 'GQ'],
            ['country_name' => 'Guinea-Bisáu', 'iso_code_2' => 'GW'],
            ['country_name' => 'Guyana', 'iso_code_2' => 'GY'],
            ['country_name' => 'Haití', 'iso_code_2' => 'HT'],
            ['country_name' => 'Honduras', 'iso_code_2' => 'HN'],
            ['country_name' => 'Hungría', 'iso_code_2' => 'HU'],
            ['country_name' => 'India', 'iso_code_2' => 'IN'],
            ['country_name' => 'Indonesia', 'iso_code_2' => 'ID'],
            ['country_name' => 'Irak', 'iso_code_2' => 'IQ'],
            ['country_name' => 'Irán', 'iso_code_2' => 'IR'],
            ['country_name' => 'Irlanda', 'iso_code_2' => 'IE'],
            ['country_name' => 'Islandia', 'iso_code_2' => 'IS'],
            ['country_name' => 'Islas Marshall', 'iso_code_2' => 'MH'],
            ['country_name' => 'Islas Salomón', 'iso_code_2' => 'SB'],
            ['country_name' => 'Israel', 'iso_code_2' => 'IL'],
            ['country_name' => 'Italia', 'iso_code_2' => 'IT'],
            ['country_name' => 'Jamaica', 'iso_code_2' => 'JM'],
            ['country_name' => 'Japón', 'iso_code_2' => 'JP'],
            ['country_name' => 'Jordania', 'iso_code_2' => 'JO'],
            ['country_name' => 'Kazajistán', 'iso_code_2' => 'KZ'],
            ['country_name' => 'Kenia', 'iso_code_2' => 'KE'],
            ['country_name' => 'Kirguistán', 'iso_code_2' => 'KG'],
            ['country_name' => 'Kiribati', 'iso_code_2' => 'KI'],
            ['country_name' => 'Kuwait', 'iso_code_2' => 'KW'],
            ['country_name' => 'Laos', 'iso_code_2' => 'LA'],
            ['country_name' => 'Lesoto', 'iso_code_2' => 'LS'],
            ['country_name' => 'Letonia', 'iso_code_2' => 'LV'],
            ['country_name' => 'Líbano', 'iso_code_2' => 'LB'],
            ['country_name' => 'Liberia', 'iso_code_2' => 'LR'],
            ['country_name' => 'Libia', 'iso_code_2' => 'LY'],
            ['country_name' => 'Liechtenstein', 'iso_code_2' => 'LI'],
            ['country_name' => 'Lituania', 'iso_code_2' => 'LT'],
            ['country_name' => 'Luxemburgo', 'iso_code_2' => 'LU'],
            ['country_name' => 'Macedonia del Norte', 'iso_code_2' => 'MK'],
            ['country_name' => 'Madagascar', 'iso_code_2' => 'MG'],
            ['country_name' => 'Malasia', 'iso_code_2' => 'MY'],
            ['country_name' => 'Malaui', 'iso_code_2' => 'MW'],
            ['country_name' => 'Maldivas', 'iso_code_2' => 'MV'],
            ['country_name' => 'Malí', 'iso_code_2' => 'ML'],
            ['country_name' => 'Malta', 'iso_code_2' => 'MT'],
            ['country_name' => 'Marruecos', 'iso_code_2' => 'MA'],
            ['country_name' => 'Mauricio', 'iso_code_2' => 'MU'],
            ['country_name' => 'Mauritania', 'iso_code_2' => 'MR'],
            ['country_name' => 'México', 'iso_code_2' => 'MX'],
            ['country_name' => 'Micronesia', 'iso_code_2' => 'FM'],
            ['country_name' => 'Moldavia', 'iso_code_2' => 'MD'],
            ['country_name' => 'Mónaco', 'iso_code_2' => 'MC'],
            ['country_name' => 'Mongolia', 'iso_code_2' => 'MN'],
            ['country_name' => 'Montenegro', 'iso_code_2' => 'ME'],
            ['country_name' => 'Mozambique', 'iso_code_2' => 'MZ'],
            ['country_name' => 'Namibia', 'iso_code_2' => 'NA'],
            ['country_name' => 'Nauru', 'iso_code_2' => 'NR'],
            ['country_name' => 'Nepal', 'iso_code_2' => 'NP'],
            ['country_name' => 'Nicaragua', 'iso_code_2' => 'NI'],
            ['country_name' => 'Níger', 'iso_code_2' => 'NE'],
            ['country_name' => 'Nigeria', 'iso_code_2' => 'NG'],
            ['country_name' => 'Noruega', 'iso_code_2' => 'NO'],
            ['country_name' => 'Nueva Zelanda', 'iso_code_2' => 'NZ'],
            ['country_name' => 'Omán', 'iso_code_2' => 'OM'],
            ['country_name' => 'Países Bajos', 'iso_code_2' => 'NL'],
            ['country_name' => 'Pakistán', 'iso_code_2' => 'PK'],
            ['country_name' => 'Palaos', 'iso_code_2' => 'PW'],
            ['country_name' => 'Palestina', 'iso_code_2' => 'PS'],
            ['country_name' => 'Panamá', 'iso_code_2' => 'PA'],
            ['country_name' => 'Papúa Nueva Guinea', 'iso_code_2' => 'PG'],
            ['country_name' => 'Paraguay', 'iso_code_2' => 'PY'],
            ['country_name' => 'Perú', 'iso_code_2' => 'PE'],
            ['country_name' => 'Polonia', 'iso_code_2' => 'PL'],
            ['country_name' => 'Portugal', 'iso_code_2' => 'PT'],
            ['country_name' => 'Reino Unido', 'iso_code_2' => 'GB'],
            ['country_name' => 'República Centroafricana', 'iso_code_2' => 'CF'],
            ['country_name' => 'República Checa', 'iso_code_2' => 'CZ'],
            ['country_name' => 'República del Congo', 'iso_code_2' => 'CG'],
            ['country_name' => 'República Democrática del Congo', 'iso_code_2' => 'CD'],
            ['country_name' => 'República Dominicana', 'iso_code_2' => 'DO'],
            ['country_name' => 'Ruanda', 'iso_code_2' => 'RW'],
            ['country_name' => 'Rumanía', 'iso_code_2' => 'RO'],
            ['country_name' => 'Rusia', 'iso_code_2' => 'RU'],
            ['country_name' => 'Samoa', 'iso_code_2' => 'WS'],
            ['country_name' => 'San Cristóbal y Nieves', 'iso_code_2' => 'KN'],
            ['country_name' => 'San Marino', 'iso_code_2' => 'SM'],
            ['country_name' => 'San Vicente y las Granadinas', 'iso_code_2' => 'VC'],
            ['country_name' => 'Santa Lucía', 'iso_code_2' => 'LC'],
            ['country_name' => 'Santo Tomé y Príncipe', 'iso_code_2' => 'ST'],
            ['country_name' => 'Senegal', 'iso_code_2' => 'SN'],
            ['country_name' => 'Serbia', 'iso_code_2' => 'RS'],
            ['country_name' => 'Seychelles', 'iso_code_2' => 'SC'],
            ['country_name' => 'Sierra Leona', 'iso_code_2' => 'SL'],
            ['country_name' => 'Singapur', 'iso_code_2' => 'SG'],
            ['country_name' => 'Siria', 'iso_code_2' => 'SY'],
            ['country_name' => 'Somalia', 'iso_code_2' => 'SO'],
            ['country_name' => 'Sri Lanka', 'iso_code_2' => 'LK'],
            ['country_name' => 'Sudáfrica', 'iso_code_2' => 'ZA'],
            ['country_name' => 'Sudán', 'iso_code_2' => 'SD'],
            ['country_name' => 'Sudán del Sur', 'iso_code_2' => 'SS'],
            ['country_name' => 'Suecia', 'iso_code_2' => 'SE'],
            ['country_name' => 'Suiza', 'iso_code_2' => 'CH'],
            ['country_name' => 'Surinam', 'iso_code_2' => 'SR'],
            ['country_name' => 'Tailandia', 'iso_code_2' => 'TH'],
            ['country_name' => 'Tanzania', 'iso_code_2' => 'TZ'],
            ['country_name' => 'Tayikistán', 'iso_code_2' => 'TJ'],
            ['country_name' => 'Timor Oriental', 'iso_code_2' => 'TL'],
            ['country_name' => 'Togo', 'iso_code_2' => 'TG'],
            ['country_name' => 'Tonga', 'iso_code_2' => 'TO'],
            ['country_name' => 'Trinidad y Tobago', 'iso_code_2' => 'TT'],
            ['country_name' => 'Túnez', 'iso_code_2' => 'TN'],
            ['country_name' => 'Turkmenistán', 'iso_code_2' => 'TM'],
            ['country_name' => 'Turquía', 'iso_code_2' => 'TR'],
            ['country_name' => 'Tuvalu', 'iso_code_2' => 'TV'],
            ['country_name' => 'Ucrania', 'iso_code_2' => 'UA'],
            ['country_name' => 'Uganda', 'iso_code_2' => 'UG'],
            ['country_name' => 'Uruguay', 'iso_code_2' => 'UY'],
            ['country_name' => 'Uzbekistán', 'iso_code_2' => 'UZ'],
            ['country_name' => 'Vanuatu', 'iso_code_2' => 'VU'],
            ['country_name' => 'Vaticano', 'iso_code_2' => 'VA'],
            ['country_name' => 'Venezuela', 'iso_code_2' => 'VE'],
            ['country_name' => 'Vietnam', 'iso_code_2' => 'VN'],
            ['country_name' => 'Yemen', 'iso_code_2' => 'YE'],
            ['country_name' => 'Yibuti', 'iso_code_2' => 'DJ'],
            ['country_name' => 'Zambia', 'iso_code_2' => 'ZM'],
            ['country_name' => 'Zimbabue', 'iso_code_2' => 'ZW'],
        ];

        foreach ($countries as $country) {
            Country::firstOrCreate(
                ['iso_code_2' => $country['iso_code_2']],
                $country
            );
        }

        $this->command->info('Seeded ' . count($countries) . ' countries.');
    }
}
