<?php

namespace Database\Seeders;

use App\Models\Municipality;
use App\Models\Province;
use Illuminate\Database\Seeder;

class MunicipalitySeeder extends Seeder
{
    /**
     * Seed the municipalities table with Spanish municipalities (INE codes).
     * Code format: 5 digits (2 province + 3 municipality)
     */
    public function run(): void
    {
        $provinces = Province::all()->keyBy('province_code');

        if ($provinces->isEmpty()) {
            $this->command->error('No provinces found. Run ProvinceSeeder first.');
            return;
        }

        // Municipios organizados por código de provincia
        $municipalitiesByProvince = $this->getMunicipalities();

        $totalCount = 0;
        foreach ($municipalitiesByProvince as $provinceCode => $municipalities) {
            $province = $provinces->get($provinceCode);
            if (!$province) {
                $this->command->warn("Province {$provinceCode} not found, skipping...");
                continue;
            }

            foreach ($municipalities as $municipality) {
                Municipality::firstOrCreate(
                    [
                        'municipality_code' => $municipality['code'],
                        'province_id' => $province->id,
                    ],
                    [
                        'municipality_name' => $municipality['name'],
                        'municipality_code' => $municipality['code'],
                        'province_id' => $province->id,
                    ]
                );
                $totalCount++;
            }
        }

        $this->command->info("Seeded {$totalCount} Spanish municipalities.");
    }

    /**
     * Get all municipalities organized by province code.
     */
    private function getMunicipalities(): array
    {
        return [
            // 01 - Álava
            '01' => [
                ['code' => '01001', 'name' => 'Alegría-Dulantzi'],
                ['code' => '01002', 'name' => 'Amurrio'],
                ['code' => '01049', 'name' => 'Vitoria-Gasteiz'],
                ['code' => '01036', 'name' => 'Llodio'],
                ['code' => '01051', 'name' => 'Salvatierra'],
            ],
            // 02 - Albacete
            '02' => [
                ['code' => '02003', 'name' => 'Albacete'],
                ['code' => '02032', 'name' => 'Hellín'],
                ['code' => '02081', 'name' => 'Villarrobledo'],
                ['code' => '02002', 'name' => 'Alcalá del Júcar'],
                ['code' => '02010', 'name' => 'Almansa'],
                ['code' => '02034', 'name' => 'La Roda'],
                ['code' => '02024', 'name' => 'Chinchilla de Monte-Aragón'],
                ['code' => '02020', 'name' => 'Casas-Ibáñez'],
                ['code' => '02023', 'name' => 'Caudete'],
            ],
            // 03 - Alicante
            '03' => [
                ['code' => '03014', 'name' => 'Alicante'],
                ['code' => '03065', 'name' => 'Elche'],
                ['code' => '03099', 'name' => 'Orihuela'],
                ['code' => '03133', 'name' => 'Torrevieja'],
                ['code' => '03031', 'name' => 'Benidorm'],
                ['code' => '03009', 'name' => 'Alcoy'],
                ['code' => '03063', 'name' => 'Elda'],
                ['code' => '03119', 'name' => 'San Vicente del Raspeig'],
                ['code' => '03047', 'name' => 'Crevillent'],
                ['code' => '03082', 'name' => 'Jávea'],
                ['code' => '03050', 'name' => 'Dénia'],
                ['code' => '03104', 'name' => 'Petrer'],
                ['code' => '03077', 'name' => 'Ibi'],
                ['code' => '03122', 'name' => 'Santa Pola'],
                ['code' => '03093', 'name' => 'Novelda'],
            ],
            // 04 - Almería
            '04' => [
                ['code' => '04013', 'name' => 'Almería'],
                ['code' => '04032', 'name' => 'El Ejido'],
                ['code' => '04066', 'name' => 'Níjar'],
                ['code' => '04079', 'name' => 'Roquetas de Mar'],
                ['code' => '04003', 'name' => 'Adra'],
                ['code' => '04902', 'name' => 'La Mojonera'],
                ['code' => '04100', 'name' => 'Vícar'],
                ['code' => '04022', 'name' => 'Berja'],
                ['code' => '04049', 'name' => 'Huércal-Overa'],
                ['code' => '04050', 'name' => 'Huércal de Almería'],
                ['code' => '04009', 'name' => 'Albox'],
                ['code' => '04028', 'name' => 'Cuevas del Almanzora'],
                ['code' => '04101', 'name' => 'Viator'],
                ['code' => '04076', 'name' => 'Pulpí'],
                ['code' => '04042', 'name' => 'Garrucha'],
                ['code' => '04058', 'name' => 'Macael'],
                ['code' => '04060', 'name' => 'Mojácar'],
                ['code' => '04029', 'name' => 'Dalías'],
                ['code' => '04017', 'name' => 'Antas'],
                ['code' => '04038', 'name' => 'Fiñana'],
                ['code' => '04078', 'name' => 'Rioja'],
                ['code' => '04044', 'name' => 'Gérgal'],
                ['code' => '04018', 'name' => 'Arboleas'],
                ['code' => '04901', 'name' => 'Balanegra'],
            ],
            // 05 - Ávila
            '05' => [
                ['code' => '05019', 'name' => 'Ávila'],
                ['code' => '05010', 'name' => 'Arévalo'],
                ['code' => '05076', 'name' => 'El Tiemblo'],
                ['code' => '05024', 'name' => 'Barco de Ávila'],
                ['code' => '05044', 'name' => 'Candeleda'],
                ['code' => '05012', 'name' => 'Arenas de San Pedro'],
            ],
            // 06 - Badajoz
            '06' => [
                ['code' => '06015', 'name' => 'Badajoz'],
                ['code' => '06083', 'name' => 'Mérida'],
                ['code' => '06044', 'name' => 'Don Benito'],
                ['code' => '06009', 'name' => 'Almendralejo'],
                ['code' => '06158', 'name' => 'Villanueva de la Serena'],
                ['code' => '06070', 'name' => 'Jerez de los Caballeros'],
                ['code' => '06160', 'name' => 'Villafranca de los Barros'],
                ['code' => '06165', 'name' => 'Zafra'],
                ['code' => '06011', 'name' => 'Azuaga'],
                ['code' => '06089', 'name' => 'Montijo'],
                ['code' => '06047', 'name' => 'Fregenal de la Sierra'],
                ['code' => '06079', 'name' => 'Llerena'],
                ['code' => '06098', 'name' => 'Olivenza'],
            ],
            // 07 - Illes Balears
            '07' => [
                ['code' => '07040', 'name' => 'Palma'],
                ['code' => '07011', 'name' => 'Calvià'],
                ['code' => '07032', 'name' => 'Manacor'],
                ['code' => '07026', 'name' => 'Ibiza'],
                ['code' => '07036', 'name' => 'Marratxí'],
                ['code' => '07031', 'name' => 'Maó-Mahón'],
                ['code' => '07033', 'name' => 'Inca'],
                ['code' => '07027', 'name' => 'Llucmajor'],
                ['code' => '07015', 'name' => 'Ciutadella de Menorca'],
                ['code' => '07051', 'name' => 'Santa Eulalia del Río'],
                ['code' => '07046', 'name' => 'Sant Antoni de Portmany'],
                ['code' => '07054', 'name' => 'Sóller'],
                ['code' => '07001', 'name' => 'Alaró'],
                ['code' => '07002', 'name' => 'Alcúdia'],
                ['code' => '07044', 'name' => 'Pollença'],
                ['code' => '07038', 'name' => 'Felanitx'],
            ],
            // 08 - Barcelona
            '08' => [
                ['code' => '08019', 'name' => 'Barcelona'],
                ['code' => '08101', 'name' => 'Hospitalet de Llobregat'],
                ['code' => '08015', 'name' => 'Badalona'],
                ['code' => '08217', 'name' => 'Sabadell'],
                ['code' => '08266', 'name' => 'Terrassa'],
                ['code' => '08245', 'name' => 'Santa Coloma de Gramenet'],
                ['code' => '08169', 'name' => 'Mataró'],
                ['code' => '08089', 'name' => 'Granollers'],
                ['code' => '08205', 'name' => 'Rubí'],
                ['code' => '08279', 'name' => 'Vilanova i la Geltrú'],
                ['code' => '08211', 'name' => 'El Prat de Llobregat'],
                ['code' => '08073', 'name' => 'Cornellà de Llobregat'],
                ['code' => '08301', 'name' => 'Sant Cugat del Vallès'],
                ['code' => '08180', 'name' => 'Mollet del Vallès'],
                ['code' => '08113', 'name' => 'Manresa'],
                ['code' => '08298', 'name' => 'Sant Boi de Llobregat'],
                ['code' => '08263', 'name' => 'Castelldefels'],
                ['code' => '08077', 'name' => 'Esplugues de Llobregat'],
                ['code' => '08252', 'name' => 'Sant Feliu de Llobregat'],
                ['code' => '08187', 'name' => 'Montcada i Reixac'],
                ['code' => '08076', 'name' => 'Cerdanyola del Vallès'],
                ['code' => '08282', 'name' => 'Viladecans'],
                ['code' => '08096', 'name' => 'Gavà'],
                ['code' => '08184', 'name' => 'Sitges'],
                ['code' => '08124', 'name' => 'Vic'],
            ],
            // 09 - Burgos
            '09' => [
                ['code' => '09059', 'name' => 'Burgos'],
                ['code' => '09018', 'name' => 'Aranda de Duero'],
                ['code' => '09219', 'name' => 'Miranda de Ebro'],
                ['code' => '09211', 'name' => 'Medina de Pomar'],
                ['code' => '09056', 'name' => 'Briviesca'],
                ['code' => '09354', 'name' => 'Salas de los Infantes'],
            ],
            // 10 - Cáceres
            '10' => [
                ['code' => '10037', 'name' => 'Cáceres'],
                ['code' => '10148', 'name' => 'Plasencia'],
                ['code' => '10131', 'name' => 'Navalmoral de la Mata'],
                ['code' => '10119', 'name' => 'Miajadas'],
                ['code' => '10067', 'name' => 'Coria'],
                ['code' => '10195', 'name' => 'Trujillo'],
                ['code' => '10206', 'name' => 'Valencia de Alcántara'],
                ['code' => '10130', 'name' => 'Moraleja'],
                ['code' => '10123', 'name' => 'Montehermoso'],
                ['code' => '10098', 'name' => 'Jaraíz de la Vera'],
            ],
            // 11 - Cádiz
            '11' => [
                ['code' => '11012', 'name' => 'Cádiz'],
                ['code' => '11020', 'name' => 'Jerez de la Frontera'],
                ['code' => '11004', 'name' => 'Algeciras'],
                ['code' => '11033', 'name' => 'San Fernando'],
                ['code' => '11008', 'name' => 'El Puerto de Santa María'],
                ['code' => '11022', 'name' => 'La Línea de la Concepción'],
                ['code' => '11015', 'name' => 'Chiclana de la Frontera'],
                ['code' => '11031', 'name' => 'Sanlúcar de Barrameda'],
                ['code' => '11027', 'name' => 'Puerto Real'],
                ['code' => '11029', 'name' => 'Rota'],
                ['code' => '11006', 'name' => 'Arcos de la Frontera'],
                ['code' => '11023', 'name' => 'Los Barrios'],
                ['code' => '11035', 'name' => 'San Roque'],
                ['code' => '11017', 'name' => 'Conil de la Frontera'],
                ['code' => '11011', 'name' => 'Barbate'],
                ['code' => '11016', 'name' => 'Chipiona'],
                ['code' => '11038', 'name' => 'Tarifa'],
                ['code' => '11039', 'name' => 'Trebujena'],
                ['code' => '11040', 'name' => 'Ubrique'],
                ['code' => '11041', 'name' => 'Vejer de la Frontera'],
                ['code' => '11024', 'name' => 'Medina Sidonia'],
                ['code' => '11025', 'name' => 'Olvera'],
                ['code' => '11042', 'name' => 'Villamartín'],
            ],
            // 12 - Castellón
            '12' => [
                ['code' => '12040', 'name' => 'Castellón de la Plana'],
                ['code' => '12126', 'name' => 'Vila-real'],
                ['code' => '12032', 'name' => 'Burriana'],
                ['code' => '12009', 'name' => 'Almassora'],
                ['code' => '12084', 'name' => 'Onda'],
                ['code' => '12027', 'name' => 'Benicàssim'],
                ['code' => '12089', 'name' => 'Peñíscola'],
                ['code' => '12124', 'name' => 'Vinaròs'],
                ['code' => '12135', 'name' => 'La Vall d\'Uixó'],
                ['code' => '12080', 'name' => 'Nules'],
                ['code' => '12026', 'name' => 'Benicarló'],
                ['code' => '12082', 'name' => 'Oropesa del Mar'],
                ['code' => '12104', 'name' => 'Segorbe'],
            ],
            // 13 - Ciudad Real
            '13' => [
                ['code' => '13034', 'name' => 'Ciudad Real'],
                ['code' => '13071', 'name' => 'Puertollano'],
                ['code' => '13097', 'name' => 'Tomelloso'],
                ['code' => '13005', 'name' => 'Alcázar de San Juan'],
                ['code' => '13099', 'name' => 'Valdepeñas'],
                ['code' => '13053', 'name' => 'Manzanares'],
                ['code' => '13038', 'name' => 'Daimiel'],
                ['code' => '13079', 'name' => 'La Solana'],
                ['code' => '13028', 'name' => 'Campo de Criptana'],
                ['code' => '13059', 'name' => 'Miguelturra'],
                ['code' => '13013', 'name' => 'Bolaños de Calatrava'],
                ['code' => '13081', 'name' => 'Socuéllamos'],
            ],
            // 14 - Córdoba
            '14' => [
                ['code' => '14021', 'name' => 'Córdoba'],
                ['code' => '14042', 'name' => 'Lucena'],
                ['code' => '14052', 'name' => 'Puente Genil'],
                ['code' => '14047', 'name' => 'Montilla'],
                ['code' => '14051', 'name' => 'Priego de Córdoba'],
                ['code' => '14010', 'name' => 'Cabra'],
                ['code' => '14006', 'name' => 'Baena'],
                ['code' => '14050', 'name' => 'Pozoblanco'],
                ['code' => '14016', 'name' => 'Castro del Río'],
                ['code' => '14056', 'name' => 'Rute'],
                ['code' => '14038', 'name' => 'La Rambla'],
                ['code' => '14045', 'name' => 'Montoro'],
                ['code' => '14001', 'name' => 'Adamuz'],
                ['code' => '14004', 'name' => 'Aguilar de la Frontera'],
                ['code' => '14007', 'name' => 'Belalcázar'],
                ['code' => '14011', 'name' => 'Cañete de las Torres'],
                ['code' => '14017', 'name' => 'Córdoba'],
                ['code' => '14020', 'name' => 'Fernán Núñez'],
                ['code' => '14023', 'name' => 'Fuente Obejuna'],
                ['code' => '14029', 'name' => 'Hinojosa del Duque'],
                ['code' => '14034', 'name' => 'Iznájar'],
                ['code' => '14046', 'name' => 'Peñarroya-Pueblonuevo'],
                ['code' => '14055', 'name' => 'Palma del Río'],
                ['code' => '14058', 'name' => 'Santaella'],
                ['code' => '14063', 'name' => 'Villanueva de Córdoba'],
            ],
            // 15 - A Coruña
            '15' => [
                ['code' => '15030', 'name' => 'A Coruña'],
                ['code' => '15078', 'name' => 'Santiago de Compostela'],
                ['code' => '15036', 'name' => 'Ferrol'],
                ['code' => '15057', 'name' => 'Narón'],
                ['code' => '15054', 'name' => 'Oleiros'],
                ['code' => '15002', 'name' => 'Arteixo'],
                ['code' => '15019', 'name' => 'Carballo'],
                ['code' => '15009', 'name' => 'Ribeira'],
                ['code' => '15012', 'name' => 'Boiro'],
                ['code' => '15001', 'name' => 'Culleredo'],
                ['code' => '15017', 'name' => 'Cambre'],
                ['code' => '15005', 'name' => 'Ames'],
                ['code' => '15076', 'name' => 'Betanzos'],
            ],
            // 16 - Cuenca
            '16' => [
                ['code' => '16078', 'name' => 'Cuenca'],
                ['code' => '16219', 'name' => 'Tarancón'],
                ['code' => '16140', 'name' => 'Motilla del Palancar'],
                ['code' => '16184', 'name' => 'Quintanar del Rey'],
                ['code' => '16193', 'name' => 'San Clemente'],
                ['code' => '16117', 'name' => 'Las Pedroñeras'],
            ],
            // 17 - Girona
            '17' => [
                ['code' => '17079', 'name' => 'Girona'],
                ['code' => '17066', 'name' => 'Figueres'],
                ['code' => '17023', 'name' => 'Blanes'],
                ['code' => '17118', 'name' => 'Lloret de Mar'],
                ['code' => '17095', 'name' => 'Olot'],
                ['code' => '17155', 'name' => 'Salt'],
                ['code' => '17160', 'name' => 'Sant Feliu de Guíxols'],
                ['code' => '17130', 'name' => 'Palafrugell'],
                ['code' => '17022', 'name' => 'Banyoles'],
                ['code' => '17114', 'name' => 'La Bisbal d\'Empordà'],
                ['code' => '17117', 'name' => 'Roses'],
                ['code' => '17048', 'name' => 'Castell-Platja d\'Aro'],
                ['code' => '17142', 'name' => 'Palamós'],
                ['code' => '17174', 'name' => 'Torroella de Montgrí'],
                ['code' => '17043', 'name' => 'Calonge i Sant Antoni'],
                ['code' => '17121', 'name' => 'Llagostera'],
                ['code' => '17147', 'name' => 'Ripoll'],
                ['code' => '17006', 'name' => 'Arbúcies'],
                ['code' => '17007', 'name' => 'Puigcerdà'],
            ],
            // 18 - Granada
            '18' => [
                ['code' => '18087', 'name' => 'Granada'],
                ['code' => '18140', 'name' => 'Motril'],
                ['code' => '18017', 'name' => 'Almuñécar'],
                ['code' => '18122', 'name' => 'Maracena'],
                ['code' => '18003', 'name' => 'Armilla'],
                ['code' => '18101', 'name' => 'Baza'],
                ['code' => '18023', 'name' => 'Loja'],
                ['code' => '18089', 'name' => 'Guadix'],
                ['code' => '18021', 'name' => 'Las Gabias'],
                ['code' => '18127', 'name' => 'Huétor Vega'],
                ['code' => '18194', 'name' => 'Santa Fe'],
                ['code' => '18006', 'name' => 'Atarfe'],
                ['code' => '18011', 'name' => 'Albolote'],
                ['code' => '18143', 'name' => 'Ogíjares'],
                ['code' => '18189', 'name' => 'Salobreña'],
                ['code' => '18082', 'name' => 'La Zubia'],
                ['code' => '18099', 'name' => 'Huétor Tájar'],
                ['code' => '18105', 'name' => 'Illora'],
                ['code' => '18044', 'name' => 'Cúllar'],
                ['code' => '18073', 'name' => 'Fuente Vaqueros'],
                ['code' => '18027', 'name' => 'Chauchina'],
                ['code' => '18139', 'name' => 'Montefrío'],
                ['code' => '18117', 'name' => 'Peligros'],
                ['code' => '18902', 'name' => 'Cenes de la Vega'],
                ['code' => '18903', 'name' => 'Vegas del Genil'],
            ],
            // 19 - Guadalajara
            '19' => [
                ['code' => '19130', 'name' => 'Guadalajara'],
                ['code' => '19016', 'name' => 'Azuqueca de Henares'],
                ['code' => '19058', 'name' => 'Cabanillas del Campo'],
                ['code' => '19011', 'name' => 'Alovera'],
                ['code' => '19046', 'name' => 'El Casar'],
                ['code' => '19178', 'name' => 'Marchamalo'],
                ['code' => '19282', 'name' => 'Sigüenza'],
                ['code' => '19214', 'name' => 'Molina de Aragón'],
            ],
            // 20 - Gipuzkoa
            '20' => [
                ['code' => '20069', 'name' => 'Donostia-San Sebastián'],
                ['code' => '20045', 'name' => 'Irun'],
                ['code' => '20018', 'name' => 'Errenteria'],
                ['code' => '20055', 'name' => 'Eibar'],
                ['code' => '20079', 'name' => 'Zarautz'],
                ['code' => '20003', 'name' => 'Arrasate/Mondragón'],
                ['code' => '20038', 'name' => 'Hernani'],
                ['code' => '20027', 'name' => 'Hondarribia'],
                ['code' => '20068', 'name' => 'Tolosa'],
                ['code' => '20006', 'name' => 'Andoain'],
                ['code' => '20067', 'name' => 'Lasarte-Oria'],
                ['code' => '20032', 'name' => 'Oñati'],
                ['code' => '20057', 'name' => 'Pasaia'],
                ['code' => '20071', 'name' => 'Bergara'],
                ['code' => '20076', 'name' => 'Azpeitia'],
                ['code' => '20077', 'name' => 'Azkoitia'],
            ],
            // 21 - Huelva (Importante para agricultura)
            '21' => [
                ['code' => '21041', 'name' => 'Huelva'],
                ['code' => '21050', 'name' => 'Lepe'],
                ['code' => '21055', 'name' => 'Moguer'],
                ['code' => '21005', 'name' => 'Almonte'],
                ['code' => '21010', 'name' => 'Ayamonte'],
                ['code' => '21044', 'name' => 'Isla Cristina'],
                ['code' => '21004', 'name' => 'Aljaraque'],
                ['code' => '21059', 'name' => 'Palos de la Frontera'],
                ['code' => '21038', 'name' => 'Gibraleón'],
                ['code' => '21060', 'name' => 'La Palma del Condado'],
                ['code' => '21014', 'name' => 'Bollullos Par del Condado'],
                ['code' => '21071', 'name' => 'San Juan del Puerto'],
                ['code' => '21020', 'name' => 'Cartaya'],
                ['code' => '21063', 'name' => 'Punta Umbría'],
                ['code' => '21012', 'name' => 'Bonares'],
                ['code' => '21051', 'name' => 'Lucena del Puerto'],
                ['code' => '21067', 'name' => 'Rociana del Condado'],
                ['code' => '21076', 'name' => 'Trigueros'],
                ['code' => '21001', 'name' => 'Alájar'],
                ['code' => '21002', 'name' => 'Aljaraque'],
                ['code' => '21003', 'name' => 'El Almendro'],
                ['code' => '21006', 'name' => 'Alosno'],
                ['code' => '21007', 'name' => 'Aracena'],
                ['code' => '21008', 'name' => 'Aroche'],
                ['code' => '21009', 'name' => 'Arroyomolinos de León'],
                ['code' => '21011', 'name' => 'Beas'],
                ['code' => '21013', 'name' => 'Berrocal'],
                ['code' => '21015', 'name' => 'Cabezas Rubias'],
                ['code' => '21016', 'name' => 'Cala'],
                ['code' => '21017', 'name' => 'Calañas'],
                ['code' => '21018', 'name' => 'El Campillo'],
                ['code' => '21019', 'name' => 'Campofrío'],
                ['code' => '21021', 'name' => 'Castaño del Robledo'],
                ['code' => '21022', 'name' => 'El Cerro de Andévalo'],
                ['code' => '21023', 'name' => 'Corteconcepción'],
                ['code' => '21024', 'name' => 'Cortegana'],
                ['code' => '21025', 'name' => 'Cortelazor'],
                ['code' => '21026', 'name' => 'Cumbres de Enmedio'],
                ['code' => '21027', 'name' => 'Cumbres de San Bartolomé'],
                ['code' => '21028', 'name' => 'Cumbres Mayores'],
                ['code' => '21029', 'name' => 'Chucena'],
                ['code' => '21030', 'name' => 'Encinasola'],
                ['code' => '21031', 'name' => 'Escacena del Campo'],
                ['code' => '21032', 'name' => 'Fuenteheridos'],
                ['code' => '21033', 'name' => 'Galaroza'],
                ['code' => '21034', 'name' => 'El Granado'],
                ['code' => '21035', 'name' => 'La Granada de Río-Tinto'],
                ['code' => '21036', 'name' => 'Higuera de la Sierra'],
                ['code' => '21037', 'name' => 'Hinojales'],
                ['code' => '21039', 'name' => 'Hinojos'],
                ['code' => '21040', 'name' => 'Jabugo'],
                ['code' => '21042', 'name' => 'Linares de la Sierra'],
                ['code' => '21043', 'name' => 'Los Marines'],
                ['code' => '21045', 'name' => 'Manzanilla'],
                ['code' => '21046', 'name' => 'Minas de Riotinto'],
                ['code' => '21047', 'name' => 'Nerva'],
                ['code' => '21048', 'name' => 'Niebla'],
                ['code' => '21049', 'name' => 'La Nava'],
                ['code' => '21052', 'name' => 'Paterna del Campo'],
                ['code' => '21053', 'name' => 'Paymogo'],
                ['code' => '21054', 'name' => 'Puebla de Guzmán'],
                ['code' => '21056', 'name' => 'Puerto Moral'],
                ['code' => '21057', 'name' => 'Rosal de la Frontera'],
                ['code' => '21058', 'name' => 'San Bartolomé de la Torre'],
                ['code' => '21061', 'name' => 'San Silvestre de Guzmán'],
                ['code' => '21062', 'name' => 'Santa Ana la Real'],
                ['code' => '21064', 'name' => 'Santa Bárbara de Casa'],
                ['code' => '21065', 'name' => 'Santa Olalla del Cala'],
                ['code' => '21066', 'name' => 'Sanlúcar de Guadiana'],
                ['code' => '21068', 'name' => 'Valdelarco'],
                ['code' => '21069', 'name' => 'Valverde del Camino'],
                ['code' => '21070', 'name' => 'Villablanca'],
                ['code' => '21072', 'name' => 'Villalba del Alcor'],
                ['code' => '21073', 'name' => 'Villanueva de las Cruces'],
                ['code' => '21074', 'name' => 'Villanueva de los Castillejos'],
                ['code' => '21075', 'name' => 'Villarrasa'],
                ['code' => '21077', 'name' => 'Zalamea la Real'],
                ['code' => '21078', 'name' => 'Zufre'],
            ],
            // 22 - Huesca
            '22' => [
                ['code' => '22125', 'name' => 'Huesca'],
                ['code' => '22158', 'name' => 'Monzón'],
                ['code' => '22066', 'name' => 'Barbastro'],
                ['code' => '22130', 'name' => 'Jaca'],
                ['code' => '22096', 'name' => 'Fraga'],
                ['code' => '22212', 'name' => 'Sabiñánigo'],
                ['code' => '22181', 'name' => 'Binéfar'],
            ],
            // 23 - Jaén
            '23' => [
                ['code' => '23050', 'name' => 'Jaén'],
                ['code' => '23055', 'name' => 'Linares'],
                ['code' => '23003', 'name' => 'Andújar'],
                ['code' => '23060', 'name' => 'Martos'],
                ['code' => '23079', 'name' => 'Úbeda'],
                ['code' => '23008', 'name' => 'Bailén'],
                ['code' => '23005', 'name' => 'Baeza'],
                ['code' => '23002', 'name' => 'Alcalá la Real'],
                ['code' => '23076', 'name' => 'Torredonjimeno'],
                ['code' => '23039', 'name' => 'La Carolina'],
                ['code' => '23052', 'name' => 'Jódar'],
                ['code' => '23081', 'name' => 'Villacarrillo'],
                ['code' => '23001', 'name' => 'Alcaudete'],
                ['code' => '23043', 'name' => 'Cazorla'],
                ['code' => '23062', 'name' => 'Mengíbar'],
                ['code' => '23075', 'name' => 'Torre del Campo'],
                ['code' => '23091', 'name' => 'Villanueva del Arzobispo'],
            ],
            // 24 - León
            '24' => [
                ['code' => '24089', 'name' => 'León'],
                ['code' => '24115', 'name' => 'Ponferrada'],
                ['code' => '24145', 'name' => 'San Andrés del Rabanedo'],
                ['code' => '24010', 'name' => 'Astorga'],
                ['code' => '24191', 'name' => 'Villaquilambre'],
                ['code' => '24023', 'name' => 'Bembibre'],
                ['code' => '24206', 'name' => 'La Bañeza'],
            ],
            // 25 - Lleida
            '25' => [
                ['code' => '25120', 'name' => 'Lleida'],
                ['code' => '25015', 'name' => 'Balaguer'],
                ['code' => '25225', 'name' => 'Tàrrega'],
                ['code' => '25139', 'name' => 'Mollerussa'],
                ['code' => '25051', 'name' => 'Cervera'],
                ['code' => '25207', 'name' => 'La Seu d\'Urgell'],
                ['code' => '25003', 'name' => 'Alcarràs'],
                ['code' => '25004', 'name' => 'Alcoletge'],
                ['code' => '25007', 'name' => 'Alpicat'],
                ['code' => '25019', 'name' => 'Bell-lloc d\'Urgell'],
                ['code' => '25126', 'name' => 'Les Borges Blanques'],
            ],
            // 26 - La Rioja
            '26' => [
                ['code' => '26089', 'name' => 'Logroño'],
                ['code' => '26034', 'name' => 'Calahorra'],
                ['code' => '26011', 'name' => 'Arnedo'],
                ['code' => '26071', 'name' => 'Haro'],
                ['code' => '26004', 'name' => 'Alfaro'],
                ['code' => '26117', 'name' => 'Nájera'],
                ['code' => '26066', 'name' => 'Ezcaray'],
                ['code' => '26088', 'name' => 'Lardero'],
            ],
            // 27 - Lugo
            '27' => [
                ['code' => '27028', 'name' => 'Lugo'],
                ['code' => '27038', 'name' => 'Monforte de Lemos'],
                ['code' => '27066', 'name' => 'Viveiro'],
                ['code' => '27057', 'name' => 'Sarria'],
                ['code' => '27065', 'name' => 'Vilalba'],
                ['code' => '27019', 'name' => 'Foz'],
                ['code' => '27051', 'name' => 'Ribadeo'],
            ],
            // 28 - Madrid
            '28' => [
                ['code' => '28079', 'name' => 'Madrid'],
                ['code' => '28092', 'name' => 'Móstoles'],
                ['code' => '28005', 'name' => 'Alcalá de Henares'],
                ['code' => '28065', 'name' => 'Fuenlabrada'],
                ['code' => '28074', 'name' => 'Leganés'],
                ['code' => '28067', 'name' => 'Getafe'],
                ['code' => '28006', 'name' => 'Alcobendas'],
                ['code' => '28148', 'name' => 'Torrejón de Ardoz'],
                ['code' => '28106', 'name' => 'Parla'],
                ['code' => '28007', 'name' => 'Alcorcón'],
                ['code' => '28123', 'name' => 'Rivas-Vaciamadrid'],
                ['code' => '28134', 'name' => 'Las Rozas de Madrid'],
                ['code' => '28115', 'name' => 'Pozuelo de Alarcón'],
                ['code' => '28049', 'name' => 'Coslada'],
                ['code' => '28137', 'name' => 'San Sebastián de los Reyes'],
                ['code' => '28113', 'name' => 'Pinto'],
                ['code' => '28158', 'name' => 'Valdemoro'],
                ['code' => '28022', 'name' => 'Boadilla del Monte'],
                ['code' => '28127', 'name' => 'Rozas de Madrid'],
                ['code' => '28047', 'name' => 'Colmenar Viejo'],
                ['code' => '28080', 'name' => 'Majadahonda'],
                ['code' => '28009', 'name' => 'Arganda del Rey'],
                ['code' => '28903', 'name' => 'Tres Cantos'],
                ['code' => '28130', 'name' => 'San Fernando de Henares'],
                ['code' => '28152', 'name' => 'Torrelodones'],
                ['code' => '28058', 'name' => 'Collado Villalba'],
                ['code' => '28068', 'name' => 'Galapagar'],
                ['code' => '28012', 'name' => 'Aranjuez'],
                ['code' => '28004', 'name' => 'Villanueva de la Cañada'],
                ['code' => '28155', 'name' => 'Navalcarnero'],
                ['code' => '28028', 'name' => 'Ciempozuelos'],
                ['code' => '28181', 'name' => 'Villanueva del Pardillo'],
                ['code' => '28167', 'name' => 'Villaviciosa de Odón'],
                ['code' => '28082', 'name' => 'Mejorada del Campo'],
                ['code' => '28014', 'name' => 'Arroyomolinos'],
                ['code' => '28036', 'name' => 'Hoyo de Manzanares'],
                ['code' => '28023', 'name' => 'Brunete'],
                ['code' => '28104', 'name' => 'Paracuellos de Jarama'],
            ],
            // 29 - Málaga
            '29' => [
                ['code' => '29067', 'name' => 'Málaga'],
                ['code' => '29069', 'name' => 'Marbella'],
                ['code' => '29901', 'name' => 'Torremolinos'],
                ['code' => '29025', 'name' => 'Benalmádena'],
                ['code' => '29051', 'name' => 'Estepona'],
                ['code' => '29070', 'name' => 'Mijas'],
                ['code' => '29094', 'name' => 'Vélez-Málaga'],
                ['code' => '29065', 'name' => 'Fuengirola'],
                ['code' => '29010', 'name' => 'Antequera'],
                ['code' => '29084', 'name' => 'Ronda'],
                ['code' => '29054', 'name' => 'Alhaurín de la Torre'],
                ['code' => '29076', 'name' => 'Nerja'],
                ['code' => '29082', 'name' => 'Rincón de la Victoria'],
                ['code' => '29011', 'name' => 'Alhaurín el Grande'],
                ['code' => '29032', 'name' => 'Cártama'],
                ['code' => '29038', 'name' => 'Coín'],
                ['code' => '29023', 'name' => 'Torrox'],
                ['code' => '29015', 'name' => 'Archidona'],
                ['code' => '29031', 'name' => 'Campillos'],
                ['code' => '29007', 'name' => 'Álora'],
            ],
            // 30 - Murcia
            '30' => [
                ['code' => '30030', 'name' => 'Murcia'],
                ['code' => '30016', 'name' => 'Cartagena'],
                ['code' => '30024', 'name' => 'Lorca'],
                ['code' => '30027', 'name' => 'Molina de Segura'],
                ['code' => '30003', 'name' => 'Águilas'],
                ['code' => '30005', 'name' => 'Alcantarilla'],
                ['code' => '30042', 'name' => 'Torre-Pacheco'],
                ['code' => '30026', 'name' => 'Mazarrón'],
                ['code' => '30019', 'name' => 'Cieza'],
                ['code' => '30012', 'name' => 'Caravaca de la Cruz'],
                ['code' => '30038', 'name' => 'San Javier'],
                ['code' => '30037', 'name' => 'Totana'],
                ['code' => '30004', 'name' => 'Alhama de Murcia'],
                ['code' => '30022', 'name' => 'Jumilla'],
                ['code' => '30044', 'name' => 'Yecla'],
                ['code' => '30021', 'name' => 'Las Torres de Cotillas'],
                ['code' => '30902', 'name' => 'Los Alcázares'],
                ['code' => '30039', 'name' => 'San Pedro del Pinatar'],
                ['code' => '30901', 'name' => 'Santomera'],
                ['code' => '30008', 'name' => 'Archena'],
                ['code' => '30010', 'name' => 'Beniel'],
                ['code' => '30011', 'name' => 'Bullas'],
                ['code' => '30013', 'name' => 'Calasparra'],
                ['code' => '30014', 'name' => 'Campos del Río'],
                ['code' => '30017', 'name' => 'Cehegín'],
                ['code' => '30018', 'name' => 'Ceutí'],
                ['code' => '30023', 'name' => 'Librilla'],
                ['code' => '30025', 'name' => 'Lorquí'],
                ['code' => '30028', 'name' => 'Moratalla'],
                ['code' => '30029', 'name' => 'Mula'],
                ['code' => '30033', 'name' => 'Puerto Lumbreras'],
                ['code' => '30035', 'name' => 'Fuente Álamo de Murcia'],
                ['code' => '30040', 'name' => 'La Unión'],
            ],
            // 31 - Navarra
            '31' => [
                ['code' => '31201', 'name' => 'Pamplona'],
                ['code' => '31232', 'name' => 'Tudela'],
                ['code' => '31049', 'name' => 'Barañáin'],
                ['code' => '31903', 'name' => 'Zizur Mayor'],
                ['code' => '31076', 'name' => 'Burlada'],
                ['code' => '31904', 'name' => 'Egüés'],
                ['code' => '31027', 'name' => 'Ansoáin'],
                ['code' => '31101', 'name' => 'Estella-Lizarra'],
                ['code' => '31907', 'name' => 'Tafalla'],
                ['code' => '31901', 'name' => 'Cintruénigo'],
                ['code' => '31902', 'name' => 'Corella'],
                ['code' => '31038', 'name' => 'Villava'],
                ['code' => '31055', 'name' => 'Berriozar'],
                ['code' => '31906', 'name' => 'Noáin'],
            ],
            // 32 - Ourense
            '32' => [
                ['code' => '32054', 'name' => 'Ourense'],
                ['code' => '32009', 'name' => 'Barbadás'],
                ['code' => '32019', 'name' => 'O Carballiño'],
                ['code' => '32088', 'name' => 'Verín'],
                ['code' => '32032', 'name' => 'Xinzo de Limia'],
                ['code' => '32001', 'name' => 'Allariz'],
                ['code' => '32012', 'name' => 'O Barco de Valdeorras'],
            ],
            // 33 - Asturias
            '33' => [
                ['code' => '33044', 'name' => 'Oviedo'],
                ['code' => '33024', 'name' => 'Gijón'],
                ['code' => '33004', 'name' => 'Avilés'],
                ['code' => '33066', 'name' => 'Siero'],
                ['code' => '33037', 'name' => 'Langreo'],
                ['code' => '33031', 'name' => 'Mieres'],
                ['code' => '33016', 'name' => 'Castrillón'],
                ['code' => '33073', 'name' => 'Villaviciosa'],
                ['code' => '33012', 'name' => 'Cangas del Narcea'],
                ['code' => '33074', 'name' => 'Corvera de Asturias'],
                ['code' => '33022', 'name' => 'Gozón'],
                ['code' => '33029', 'name' => 'Llanera'],
                ['code' => '33036', 'name' => 'Laviana'],
                ['code' => '33046', 'name' => 'Pravia'],
                ['code' => '33019', 'name' => 'Carreño'],
                ['code' => '33063', 'name' => 'San Martín del Rey Aurelio'],
                ['code' => '33043', 'name' => 'Noreña'],
                ['code' => '33076', 'name' => 'Llanes'],
            ],
            // 34 - Palencia
            '34' => [
                ['code' => '34120', 'name' => 'Palencia'],
                ['code' => '34004', 'name' => 'Aguilar de Campoo'],
                ['code' => '34070', 'name' => 'Guardo'],
                ['code' => '34215', 'name' => 'Venta de Baños'],
            ],
            // 35 - Las Palmas
            '35' => [
                ['code' => '35016', 'name' => 'Las Palmas de Gran Canaria'],
                ['code' => '35026', 'name' => 'Telde'],
                ['code' => '35019', 'name' => 'Santa Lucía de Tirajana'],
                ['code' => '35004', 'name' => 'Arrecife'],
                ['code' => '35011', 'name' => 'Ingenio'],
                ['code' => '35006', 'name' => 'San Bartolomé de Tirajana'],
                ['code' => '35001', 'name' => 'Agüimes'],
                ['code' => '35014', 'name' => 'Mogán'],
                ['code' => '35015', 'name' => 'Pájara'],
                ['code' => '35020', 'name' => 'Puerto del Rosario'],
                ['code' => '35002', 'name' => 'Agaete'],
                ['code' => '35005', 'name' => 'Arucas'],
                ['code' => '35009', 'name' => 'Gáldar'],
                ['code' => '35012', 'name' => 'La Oliva'],
                ['code' => '35022', 'name' => 'Teguise'],
                ['code' => '35027', 'name' => 'Teror'],
                ['code' => '35028', 'name' => 'Tías'],
                ['code' => '35024', 'name' => 'Tuineje'],
                ['code' => '35017', 'name' => 'Puerto del Carmen'],
                ['code' => '35029', 'name' => 'Valsequillo de Gran Canaria'],
            ],
            // 36 - Pontevedra
            '36' => [
                ['code' => '36057', 'name' => 'Vigo'],
                ['code' => '36038', 'name' => 'Pontevedra'],
                ['code' => '36039', 'name' => 'Porriño'],
                ['code' => '36051', 'name' => 'Vilagarcía de Arousa'],
                ['code' => '36024', 'name' => 'Marín'],
                ['code' => '36005', 'name' => 'Cangas'],
                ['code' => '36042', 'name' => 'Redondela'],
                ['code' => '36035', 'name' => 'Ponteareas'],
                ['code' => '36053', 'name' => 'Moaña'],
                ['code' => '36033', 'name' => 'Nigrán'],
                ['code' => '36055', 'name' => 'Lalín'],
                ['code' => '36020', 'name' => 'A Estrada'],
                ['code' => '36011', 'name' => 'O Grove'],
                ['code' => '36017', 'name' => 'Gondomar'],
                ['code' => '36044', 'name' => 'Salvaterra de Miño'],
                ['code' => '36049', 'name' => 'Tui'],
                ['code' => '36003', 'name' => 'Baiona'],
                ['code' => '36004', 'name' => 'Bueu'],
                ['code' => '36007', 'name' => 'Cambados'],
                ['code' => '36043', 'name' => 'Sanxenxo'],
            ],
            // 37 - Salamanca
            '37' => [
                ['code' => '37274', 'name' => 'Salamanca'],
                ['code' => '37046', 'name' => 'Béjar'],
                ['code' => '37087', 'name' => 'Ciudad Rodrigo'],
                ['code' => '37285', 'name' => 'Santa Marta de Tormes'],
                ['code' => '37367', 'name' => 'Villares de la Reina'],
                ['code' => '37076', 'name' => 'Carbajosa de la Sagrada'],
            ],
            // 38 - Santa Cruz de Tenerife
            '38' => [
                ['code' => '38038', 'name' => 'Santa Cruz de Tenerife'],
                ['code' => '38023', 'name' => 'San Cristóbal de La Laguna'],
                ['code' => '38006', 'name' => 'Arona'],
                ['code' => '38001', 'name' => 'Adeje'],
                ['code' => '38017', 'name' => 'Granadilla de Abona'],
                ['code' => '38026', 'name' => 'La Orotava'],
                ['code' => '38032', 'name' => 'Puerto de la Cruz'],
                ['code' => '38024', 'name' => 'Los Llanos de Aridane'],
                ['code' => '38011', 'name' => 'Candelaria'],
                ['code' => '38034', 'name' => 'Los Realejos'],
                ['code' => '38031', 'name' => 'El Rosario'],
                ['code' => '38035', 'name' => 'San Miguel de Abona'],
                ['code' => '38039', 'name' => 'Santiago del Teide'],
                ['code' => '38043', 'name' => 'Tacoronte'],
                ['code' => '38044', 'name' => 'El Tanque'],
                ['code' => '38020', 'name' => 'Guía de Isora'],
                ['code' => '38012', 'name' => 'El Paso'],
                ['code' => '38022', 'name' => 'Icod de los Vinos'],
                ['code' => '38025', 'name' => 'San Sebastián de La Gomera'],
                ['code' => '38052', 'name' => 'Valverde'],
            ],
            // 39 - Cantabria
            '39' => [
                ['code' => '39075', 'name' => 'Santander'],
                ['code' => '39087', 'name' => 'Torrelavega'],
                ['code' => '39016', 'name' => 'Camargo'],
                ['code' => '39020', 'name' => 'Castro-Urdiales'],
                ['code' => '39008', 'name' => 'Astillero'],
                ['code' => '39059', 'name' => 'Piélagos'],
                ['code' => '39035', 'name' => 'Laredo'],
                ['code' => '39073', 'name' => 'Santa Cruz de Bezana'],
                ['code' => '39055', 'name' => 'Los Corrales de Buelna'],
                ['code' => '39080', 'name' => 'Santoña'],
                ['code' => '39027', 'name' => 'Colindres'],
                ['code' => '39032', 'name' => 'Reinosa'],
            ],
            // 40 - Segovia
            '40' => [
                ['code' => '40194', 'name' => 'Segovia'],
                ['code' => '40063', 'name' => 'Cuéllar'],
                ['code' => '40134', 'name' => 'El Espinar'],
                ['code' => '40906', 'name' => 'San Ildefonso'],
                ['code' => '40048', 'name' => 'Cantalejo'],
            ],
            // 41 - Sevilla
            '41' => [
                ['code' => '41091', 'name' => 'Sevilla'],
                ['code' => '41038', 'name' => 'Dos Hermanas'],
                ['code' => '41004', 'name' => 'Alcalá de Guadaíra'],
                ['code' => '41095', 'name' => 'Utrera'],
                ['code' => '41065', 'name' => 'Mairena del Aljarafe'],
                ['code' => '41053', 'name' => 'La Rinconada'],
                ['code' => '41034', 'name' => 'Écija'],
                ['code' => '41043', 'name' => 'Los Palacios y Villafranca'],
                ['code' => '41055', 'name' => 'Camas'],
                ['code' => '41024', 'name' => 'Carmona'],
                ['code' => '41014', 'name' => 'Bormujos'],
                ['code' => '41019', 'name' => 'Coria del Río'],
                ['code' => '41059', 'name' => 'Lebrija'],
                ['code' => '41080', 'name' => 'San Juan de Aznalfarache'],
                ['code' => '41061', 'name' => 'Marchena'],
                ['code' => '41066', 'name' => 'Morón de la Frontera'],
                ['code' => '41060', 'name' => 'Mairena del Alcor'],
                ['code' => '41010', 'name' => 'Arahal'],
                ['code' => '41049', 'name' => 'Guillena'],
                ['code' => '41013', 'name' => 'Bollullos de la Mitación'],
                ['code' => '41079', 'name' => 'Pilas'],
                ['code' => '41006', 'name' => 'Osuna'],
                ['code' => '41092', 'name' => 'Tomares'],
                ['code' => '41003', 'name' => 'Espartinas'],
                ['code' => '41088', 'name' => 'Sanlúcar la Mayor'],
                ['code' => '41021', 'name' => 'Castilleja de la Cuesta'],
                ['code' => '41058', 'name' => 'Lora del Río'],
                ['code' => '41044', 'name' => 'Gines'],
                ['code' => '41047', 'name' => 'Puebla del Río'],
                ['code' => '41015', 'name' => 'Brenes'],
                ['code' => '41018', 'name' => 'Constantina'],
                ['code' => '41017', 'name' => 'Cazalla de la Sierra'],
                ['code' => '41005', 'name' => 'Alcalá del Río'],
                ['code' => '41009', 'name' => 'Almensilla'],
                ['code' => '41012', 'name' => 'Benacazón'],
                ['code' => '41016', 'name' => 'Cantillana'],
                ['code' => '41020', 'name' => 'Castilblanco de los Arroyos'],
                ['code' => '41022', 'name' => 'Castilleja de Guzmán'],
                ['code' => '41023', 'name' => 'Cabezas de San Juan'],
                ['code' => '41026', 'name' => 'Estepa'],
                ['code' => '41028', 'name' => 'Fuentes de Andalucía'],
                ['code' => '41029', 'name' => 'Gelves'],
                ['code' => '41030', 'name' => 'Gerena'],
                ['code' => '41035', 'name' => 'Herrera'],
                ['code' => '41037', 'name' => 'Isla Mayor'],
                ['code' => '41048', 'name' => 'El Viso del Alcor'],
                ['code' => '41051', 'name' => 'Olivares'],
                ['code' => '41052', 'name' => 'Palomares del Río'],
                ['code' => '41054', 'name' => 'Peñaflor'],
                ['code' => '41056', 'name' => 'Lantejuela'],
                ['code' => '41062', 'name' => 'Marinaleda'],
                ['code' => '41063', 'name' => 'Martín de la Jara'],
                ['code' => '41068', 'name' => 'Navas de la Concepción'],
                ['code' => '41069', 'name' => 'Nerva'],
                ['code' => '41071', 'name' => 'Paradas'],
                ['code' => '41072', 'name' => 'Pedrera'],
                ['code' => '41075', 'name' => 'Pruna'],
                ['code' => '41076', 'name' => 'Puebla de Cazalla'],
                ['code' => '41078', 'name' => 'Puebla de los Infantes'],
                ['code' => '41081', 'name' => 'Salteras'],
                ['code' => '41083', 'name' => 'San Nicolás del Puerto'],
                ['code' => '41086', 'name' => 'Santiponce'],
                ['code' => '41089', 'name' => 'Umbrete'],
                ['code' => '41093', 'name' => 'Valencina de la Concepción'],
                ['code' => '41094', 'name' => 'Villamanrique de la Condesa'],
                ['code' => '41096', 'name' => 'Villanueva del Ariscal'],
                ['code' => '41097', 'name' => 'Villanueva del Río y Minas'],
                ['code' => '41098', 'name' => 'Villaverde del Río'],
            ],
            // 42 - Soria
            '42' => [
                ['code' => '42173', 'name' => 'Soria'],
                ['code' => '42012', 'name' => 'Almazán'],
                ['code' => '42020', 'name' => 'El Burgo de Osma-Ciudad de Osma'],
            ],
            // 43 - Tarragona
            '43' => [
                ['code' => '43148', 'name' => 'Tarragona'],
                ['code' => '43123', 'name' => 'Reus'],
                ['code' => '43163', 'name' => 'Tortosa'],
                ['code' => '43031', 'name' => 'Cambrils'],
                ['code' => '43095', 'name' => 'El Vendrell'],
                ['code' => '43905', 'name' => 'Salou'],
                ['code' => '43171', 'name' => 'Valls'],
                ['code' => '43161', 'name' => 'Vila-seca'],
                ['code' => '43014', 'name' => 'Amposta'],
                ['code' => '43038', 'name' => 'Calafell'],
                ['code' => '43044', 'name' => 'Cunit'],
                ['code' => '43153', 'name' => 'Torredembarra'],
                ['code' => '43901', 'name' => 'Sant Carles de la Ràpita'],
                ['code' => '43006', 'name' => 'Altafulla'],
                ['code' => '43047', 'name' => 'L\'Ametlla de Mar'],
            ],
            // 44 - Teruel
            '44' => [
                ['code' => '44216', 'name' => 'Teruel'],
                ['code' => '44009', 'name' => 'Alcañiz'],
                ['code' => '44025', 'name' => 'Andorra'],
                ['code' => '44034', 'name' => 'Calamocha'],
            ],
            // 45 - Toledo
            '45' => [
                ['code' => '45168', 'name' => 'Toledo'],
                ['code' => '45165', 'name' => 'Talavera de la Reina'],
                ['code' => '45081', 'name' => 'Illescas'],
                ['code' => '45153', 'name' => 'Seseña'],
                ['code' => '45189', 'name' => 'Torrijos'],
                ['code' => '45137', 'name' => 'Quintanar de la Orden'],
                ['code' => '45121', 'name' => 'Ocaña'],
                ['code' => '45059', 'name' => 'Fuensalida'],
                ['code' => '45166', 'name' => 'Tembleque'],
                ['code' => '45068', 'name' => 'Consuegra'],
                ['code' => '45173', 'name' => 'Villacañas'],
                ['code' => '45099', 'name' => 'Mora'],
                ['code' => '45095', 'name' => 'Madridejos'],
                ['code' => '45084', 'name' => 'La Puebla de Montalbán'],
                ['code' => '45180', 'name' => 'Sonseca'],
                ['code' => '45144', 'name' => 'Santa Cruz de la Zarza'],
                ['code' => '45103', 'name' => 'Numancia de la Sagra'],
                ['code' => '45067', 'name' => 'Bargas'],
                ['code' => '45019', 'name' => 'Añover de Tajo'],
                ['code' => '45202', 'name' => 'Yuncler'],
                ['code' => '45207', 'name' => 'Yuncos'],
            ],
            // 46 - Valencia
            '46' => [
                ['code' => '46250', 'name' => 'Valencia'],
                ['code' => '46131', 'name' => 'Gandía'],
                ['code' => '46220', 'name' => 'Sagunto'],
                ['code' => '46190', 'name' => 'Paterna'],
                ['code' => '46244', 'name' => 'Torrent'],
                ['code' => '46017', 'name' => 'Alzira'],
                ['code' => '46102', 'name' => 'Burjassot'],
                ['code' => '46094', 'name' => 'Mislata'],
                ['code' => '46078', 'name' => 'Catarroja'],
                ['code' => '46169', 'name' => 'Ontinyent'],
                ['code' => '46015', 'name' => 'Aldaia'],
                ['code' => '46110', 'name' => 'Quart de Poblet'],
                ['code' => '46147', 'name' => 'Manises'],
                ['code' => '46260', 'name' => 'Xirivella'],
                ['code' => '46021', 'name' => 'Alaquàs'],
                ['code' => '46022', 'name' => 'Albalat dels Sorells'],
                ['code' => '46025', 'name' => 'Alboraia'],
                ['code' => '46033', 'name' => 'Alfafar'],
                ['code' => '46044', 'name' => 'Almussafes'],
                ['code' => '46054', 'name' => 'Benetússer'],
                ['code' => '46084', 'name' => 'Cullera'],
                ['code' => '46105', 'name' => 'Canals'],
                ['code' => '46126', 'name' => 'Xàtiva'],
                ['code' => '46145', 'name' => 'Llíria'],
                ['code' => '46159', 'name' => 'Massamagrell'],
                ['code' => '46164', 'name' => 'Moncada'],
                ['code' => '46167', 'name' => 'Oliva'],
                ['code' => '46186', 'name' => 'Paiporta'],
                ['code' => '46193', 'name' => 'Picanya'],
                ['code' => '46194', 'name' => 'Picassent'],
                ['code' => '46219', 'name' => 'Requena'],
                ['code' => '46223', 'name' => 'Riba-roja de Túria'],
                ['code' => '46230', 'name' => 'Sedaví'],
                ['code' => '46233', 'name' => 'Silla'],
                ['code' => '46237', 'name' => 'Sueca'],
                ['code' => '46242', 'name' => 'Tavernes Blanques'],
                ['code' => '46252', 'name' => 'Utiel'],
            ],
            // 47 - Valladolid
            '47' => [
                ['code' => '47186', 'name' => 'Valladolid'],
                ['code' => '47085', 'name' => 'Laguna de Duero'],
                ['code' => '47101', 'name' => 'Medina del Campo'],
                ['code' => '47002', 'name' => 'Arroyo de la Encomienda'],
                ['code' => '47165', 'name' => 'Tudela de Duero'],
                ['code' => '47072', 'name' => 'Íscar'],
                ['code' => '47046', 'name' => 'Cigales'],
                ['code' => '47138', 'name' => 'Simancas'],
                ['code' => '47095', 'name' => 'Mayorga'],
                ['code' => '47179', 'name' => 'Peñafiel'],
                ['code' => '47162', 'name' => 'Tordesillas'],
                ['code' => '47070', 'name' => 'Zaratán'],
            ],
            // 48 - Bizkaia
            '48' => [
                ['code' => '48020', 'name' => 'Bilbao'],
                ['code' => '48015', 'name' => 'Barakaldo'],
                ['code' => '48044', 'name' => 'Getxo'],
                ['code' => '48078', 'name' => 'Portugalete'],
                ['code' => '48084', 'name' => 'Santurtzi'],
                ['code' => '48091', 'name' => 'Sestao'],
                ['code' => '48054', 'name' => 'Leioa'],
                ['code' => '48036', 'name' => 'Durango'],
                ['code' => '48016', 'name' => 'Basauri'],
                ['code' => '48027', 'name' => 'Erandio'],
                ['code' => '48043', 'name' => 'Galdakao'],
                ['code' => '48049', 'name' => 'Gernika-Lumo'],
                ['code' => '48012', 'name' => 'Amorebieta-Etxano'],
                ['code' => '48033', 'name' => 'Mungia'],
                ['code' => '48089', 'name' => 'Sopelana'],
                ['code' => '48096', 'name' => 'Bermeo'],
                ['code' => '48008', 'name' => 'Ondarroa'],
                ['code' => '48067', 'name' => 'Arrigorriaga'],
                ['code' => '48017', 'name' => 'Berango'],
                ['code' => '48021', 'name' => 'Derio'],
            ],
            // 49 - Zamora
            '49' => [
                ['code' => '49275', 'name' => 'Zamora'],
                ['code' => '49021', 'name' => 'Benavente'],
                ['code' => '49219', 'name' => 'Toro'],
            ],
            // 50 - Zaragoza
            '50' => [
                ['code' => '50297', 'name' => 'Zaragoza'],
                ['code' => '50067', 'name' => 'Calatayud'],
                ['code' => '50095', 'name' => 'Ejea de los Caballeros'],
                ['code' => '50272', 'name' => 'Utebo'],
                ['code' => '50252', 'name' => 'Tarazona'],
                ['code' => '50073', 'name' => 'Caspe'],
                ['code' => '50120', 'name' => 'Fraga'],
                ['code' => '50032', 'name' => 'Cuarte de Huerva'],
                ['code' => '50008', 'name' => 'Alagón'],
                ['code' => '50131', 'name' => 'La Almunia de Doña Godina'],
                ['code' => '50027', 'name' => 'Borja'],
                ['code' => '50195', 'name' => 'María de Huerva'],
                ['code' => '50094', 'name' => 'La Puebla de Alfindén'],
                ['code' => '50220', 'name' => 'Pinseque'],
                ['code' => '50078', 'name' => 'Zuera'],
                ['code' => '50110', 'name' => 'Épila'],
                ['code' => '50155', 'name' => 'Illueca'],
                ['code' => '50126', 'name' => 'Gallur'],
                ['code' => '50167', 'name' => 'Mallén'],
            ],
            // 51 - Ceuta
            '51' => [
                ['code' => '51001', 'name' => 'Ceuta'],
            ],
            // 52 - Melilla
            '52' => [
                ['code' => '52001', 'name' => 'Melilla'],
            ],
        ];
    }
}
